// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldReconciled holds the string denoting the reconciled field in the database.
	FieldReconciled = "reconciled"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldCategoryAssignedBy holds the string denoting the category_assigned_by field in the database.
	FieldCategoryAssignedBy = "category_assigned_by"
	// FieldCategoryAssignedAt holds the string denoting the category_assigned_at field in the database.
	FieldCategoryAssignedAt = "category_assigned_at"
	// FieldExternalRefProvider holds the string denoting the external_ref_provider field in the database.
	FieldExternalRefProvider = "external_ref_provider"
	// FieldExternalRefProviderTransactionID holds the string denoting the external_ref_provider_transaction_id field in the database.
	FieldExternalRefProviderTransactionID = "external_ref_provider_transaction_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the transaction in the database.
	Table = "transactions"
)

// Columns holds all SQL columns for transaction fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAccountID,
	FieldAmount,
	FieldCurrency,
	FieldOccurredAt,
	FieldDescription,
	FieldReconciled,
	FieldCategoryID,
	FieldCategoryAssignedBy,
	FieldCategoryAssignedAt,
	FieldExternalRefProvider,
	FieldExternalRefProviderTransactionID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReconciled holds the default value on creation for the "reconciled" field.
	DefaultReconciled bool
	// DefaultCategoryAssignedBy holds the default value on creation for the "category_assigned_by" field.
	DefaultCategoryAssignedBy string
	// DefaultExternalRefProvider holds the default value on creation for the "external_ref_provider" field.
	DefaultExternalRefProvider string
	// DefaultExternalRefProviderTransactionID holds the default value on creation for the "external_ref_provider_transaction_id" field.
	DefaultExternalRefProviderTransactionID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Transaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByReconciled orders the results by the reconciled field.
func ByReconciled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReconciled, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByCategoryAssignedBy orders the results by the category_assigned_by field.
func ByCategoryAssignedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryAssignedBy, opts...).ToFunc()
}

// ByCategoryAssignedAt orders the results by the category_assigned_at field.
func ByCategoryAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryAssignedAt, opts...).ToFunc()
}

// ByExternalRefProvider orders the results by the external_ref_provider field.
func ByExternalRefProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalRefProvider, opts...).ToFunc()
}

// ByExternalRefProviderTransactionID orders the results by the external_ref_provider_transaction_id field.
func ByExternalRefProviderTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalRefProviderTransactionID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
