// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldAccountID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCurrency, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldOccurredAt, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldDescription, v))
}

// Reconciled applies equality check predicate on the "reconciled" field. It's identical to ReconciledEQ.
func Reconciled(v bool) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldReconciled, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryAssignedBy applies equality check predicate on the "category_assigned_by" field. It's identical to CategoryAssignedByEQ.
func CategoryAssignedBy(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryAssignedBy, v))
}

// CategoryAssignedAt applies equality check predicate on the "category_assigned_at" field. It's identical to CategoryAssignedAtEQ.
func CategoryAssignedAt(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryAssignedAt, v))
}

// ExternalRefProvider applies equality check predicate on the "external_ref_provider" field. It's identical to ExternalRefProviderEQ.
func ExternalRefProvider(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldExternalRefProvider, v))
}

// ExternalRefProviderTransactionID applies equality check predicate on the "external_ref_provider_transaction_id" field. It's identical to ExternalRefProviderTransactionIDEQ.
func ExternalRefProviderTransactionID(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldExternalRefProviderTransactionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldAccountID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContainsFold(FieldCurrency, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldOccurredAt, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContainsFold(FieldDescription, v))
}

// ReconciledEQ applies the EQ predicate on the "reconciled" field.
func ReconciledEQ(v bool) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldReconciled, v))
}

// ReconciledNEQ applies the NEQ predicate on the "reconciled" field.
func ReconciledNEQ(v bool) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldReconciled, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v uuid.UUID) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldCategoryID, v))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.Transaction {
	return predicate.Transaction(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.Transaction {
	return predicate.Transaction(sql.FieldNotNull(FieldCategoryID))
}

// CategoryAssignedByEQ applies the EQ predicate on the "category_assigned_by" field.
func CategoryAssignedByEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByNEQ applies the NEQ predicate on the "category_assigned_by" field.
func CategoryAssignedByNEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByIn applies the In predicate on the "category_assigned_by" field.
func CategoryAssignedByIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldCategoryAssignedBy, vs...))
}

// CategoryAssignedByNotIn applies the NotIn predicate on the "category_assigned_by" field.
func CategoryAssignedByNotIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldCategoryAssignedBy, vs...))
}

// CategoryAssignedByGT applies the GT predicate on the "category_assigned_by" field.
func CategoryAssignedByGT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByGTE applies the GTE predicate on the "category_assigned_by" field.
func CategoryAssignedByGTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByLT applies the LT predicate on the "category_assigned_by" field.
func CategoryAssignedByLT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByLTE applies the LTE predicate on the "category_assigned_by" field.
func CategoryAssignedByLTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByContains applies the Contains predicate on the "category_assigned_by" field.
func CategoryAssignedByContains(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContains(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByHasPrefix applies the HasPrefix predicate on the "category_assigned_by" field.
func CategoryAssignedByHasPrefix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasPrefix(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByHasSuffix applies the HasSuffix predicate on the "category_assigned_by" field.
func CategoryAssignedByHasSuffix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasSuffix(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByEqualFold applies the EqualFold predicate on the "category_assigned_by" field.
func CategoryAssignedByEqualFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEqualFold(FieldCategoryAssignedBy, v))
}

// CategoryAssignedByContainsFold applies the ContainsFold predicate on the "category_assigned_by" field.
func CategoryAssignedByContainsFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContainsFold(FieldCategoryAssignedBy, v))
}

// CategoryAssignedAtEQ applies the EQ predicate on the "category_assigned_at" field.
func CategoryAssignedAtEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtNEQ applies the NEQ predicate on the "category_assigned_at" field.
func CategoryAssignedAtNEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtIn applies the In predicate on the "category_assigned_at" field.
func CategoryAssignedAtIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldCategoryAssignedAt, vs...))
}

// CategoryAssignedAtNotIn applies the NotIn predicate on the "category_assigned_at" field.
func CategoryAssignedAtNotIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldCategoryAssignedAt, vs...))
}

// CategoryAssignedAtGT applies the GT predicate on the "category_assigned_at" field.
func CategoryAssignedAtGT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtGTE applies the GTE predicate on the "category_assigned_at" field.
func CategoryAssignedAtGTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtLT applies the LT predicate on the "category_assigned_at" field.
func CategoryAssignedAtLT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtLTE applies the LTE predicate on the "category_assigned_at" field.
func CategoryAssignedAtLTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldCategoryAssignedAt, v))
}

// CategoryAssignedAtIsNil applies the IsNil predicate on the "category_assigned_at" field.
func CategoryAssignedAtIsNil() predicate.Transaction {
	return predicate.Transaction(sql.FieldIsNull(FieldCategoryAssignedAt))
}

// CategoryAssignedAtNotNil applies the NotNil predicate on the "category_assigned_at" field.
func CategoryAssignedAtNotNil() predicate.Transaction {
	return predicate.Transaction(sql.FieldNotNull(FieldCategoryAssignedAt))
}

// ExternalRefProviderEQ applies the EQ predicate on the "external_ref_provider" field.
func ExternalRefProviderEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldExternalRefProvider, v))
}

// ExternalRefProviderNEQ applies the NEQ predicate on the "external_ref_provider" field.
func ExternalRefProviderNEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldExternalRefProvider, v))
}

// ExternalRefProviderIn applies the In predicate on the "external_ref_provider" field.
func ExternalRefProviderIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldExternalRefProvider, vs...))
}

// ExternalRefProviderNotIn applies the NotIn predicate on the "external_ref_provider" field.
func ExternalRefProviderNotIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldExternalRefProvider, vs...))
}

// ExternalRefProviderGT applies the GT predicate on the "external_ref_provider" field.
func ExternalRefProviderGT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldExternalRefProvider, v))
}

// ExternalRefProviderGTE applies the GTE predicate on the "external_ref_provider" field.
func ExternalRefProviderGTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldExternalRefProvider, v))
}

// ExternalRefProviderLT applies the LT predicate on the "external_ref_provider" field.
func ExternalRefProviderLT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldExternalRefProvider, v))
}

// ExternalRefProviderLTE applies the LTE predicate on the "external_ref_provider" field.
func ExternalRefProviderLTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldExternalRefProvider, v))
}

// ExternalRefProviderContains applies the Contains predicate on the "external_ref_provider" field.
func ExternalRefProviderContains(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContains(FieldExternalRefProvider, v))
}

// ExternalRefProviderHasPrefix applies the HasPrefix predicate on the "external_ref_provider" field.
func ExternalRefProviderHasPrefix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasPrefix(FieldExternalRefProvider, v))
}

// ExternalRefProviderHasSuffix applies the HasSuffix predicate on the "external_ref_provider" field.
func ExternalRefProviderHasSuffix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasSuffix(FieldExternalRefProvider, v))
}

// ExternalRefProviderEqualFold applies the EqualFold predicate on the "external_ref_provider" field.
func ExternalRefProviderEqualFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEqualFold(FieldExternalRefProvider, v))
}

// ExternalRefProviderContainsFold applies the ContainsFold predicate on the "external_ref_provider" field.
func ExternalRefProviderContainsFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContainsFold(FieldExternalRefProvider, v))
}

// ExternalRefProviderTransactionIDEQ applies the EQ predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDNEQ applies the NEQ predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDNEQ(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDIn applies the In predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldExternalRefProviderTransactionID, vs...))
}

// ExternalRefProviderTransactionIDNotIn applies the NotIn predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDNotIn(vs ...string) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldExternalRefProviderTransactionID, vs...))
}

// ExternalRefProviderTransactionIDGT applies the GT predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDGT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDGTE applies the GTE predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDGTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDLT applies the LT predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDLT(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDLTE applies the LTE predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDLTE(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDContains applies the Contains predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDContains(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContains(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDHasPrefix applies the HasPrefix predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDHasPrefix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasPrefix(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDHasSuffix applies the HasSuffix predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDHasSuffix(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldHasSuffix(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDEqualFold applies the EqualFold predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDEqualFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldEqualFold(FieldExternalRefProviderTransactionID, v))
}

// ExternalRefProviderTransactionIDContainsFold applies the ContainsFold predicate on the "external_ref_provider_transaction_id" field.
func ExternalRefProviderTransactionIDContainsFold(v string) predicate.Transaction {
	return predicate.Transaction(sql.FieldContainsFold(FieldExternalRefProviderTransactionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Transaction {
	return predicate.Transaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Transaction) predicate.Transaction {
	return predicate.Transaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Transaction) predicate.Transaction {
	return predicate.Transaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Transaction) predicate.Transaction {
	return predicate.Transaction(sql.NotPredicates(p))
}
