// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "balance_amount", Type: field.TypeInt64},
		{Name: "balance_currency", Type: field.TypeString},
		{Name: "balance_as_of", Type: field.TypeTime},
		{Name: "source_provider", Type: field.TypeString, Default: ""},
		{Name: "source_provider_account_id", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "account_user_id",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[1]},
			},
			{
				Name:    "account_source_provider_source_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[7], AccountsColumns[8]},
				Annotation: &entsql.IndexAnnotation{
					Where: "source_provider <> ''",
				},
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "category_user_id",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[1]},
			},
			{
				Name:    "category_parent_id",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[3]},
			},
		},
	}
	// CategoryRulesColumns holds the columns for the "category_rules" table.
	CategoryRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "keyword", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "category_id", Type: field.TypeUUID},
	}
	// CategoryRulesTable holds the schema information for the "category_rules" table.
	CategoryRulesTable = &schema.Table{
		Name:       "category_rules",
		Columns:    CategoryRulesColumns,
		PrimaryKey: []*schema.Column{CategoryRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "category_rules_categories_rules",
				Columns:    []*schema.Column{CategoryRulesColumns[3]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "categoryrule_category_id_keyword",
				Unique:  true,
				Columns: []*schema.Column{CategoryRulesColumns[3], CategoryRulesColumns[1]},
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "account_id", Type: field.TypeUUID},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString},
		{Name: "reconciled", Type: field.TypeBool, Default: false},
		{Name: "category_id", Type: field.TypeUUID, Nullable: true},
		{Name: "category_assigned_by", Type: field.TypeString, Default: ""},
		{Name: "category_assigned_at", Type: field.TypeTime, Nullable: true},
		{Name: "external_ref_provider", Type: field.TypeString, Default: ""},
		{Name: "external_ref_provider_transaction_id", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "transaction_user_id_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[1], TransactionsColumns[5]},
			},
			{
				Name:    "transaction_account_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[2]},
			},
			{
				Name:    "transaction_category_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		CategoriesTable,
		CategoryRulesTable,
		TransactionsTable,
	}
)

func init() {
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	AccountsTable.Annotation.Checks = map[string]string{
		"accounts_name_not_blank": "btrim(name) <> ''",
		"accounts_source_pair":    "(source_provider = '' AND source_provider_account_id = '') OR (source_provider <> '' AND source_provider_account_id <> '')",
	}
	CategoriesTable.Annotation = &entsql.Annotation{
		Table: "categories",
	}
	CategoriesTable.Annotation.Checks = map[string]string{
		"categories_name_not_blank":  "btrim(name) <> ''",
		"categories_parent_not_self": "parent_id IS NULL OR parent_id <> id",
	}
	CategoryRulesTable.ForeignKeys[0].RefTable = CategoriesTable
	CategoryRulesTable.Annotation = &entsql.Annotation{
		Table: "category_rules",
	}
	CategoryRulesTable.Annotation.Checks = map[string]string{
		"category_rules_keyword_not_blank": "btrim(keyword) <> ''",
	}
	TransactionsTable.Annotation = &entsql.Annotation{
		Table: "transactions",
	}
	TransactionsTable.Annotation.Checks = map[string]string{
		"transactions_amount_not_zero":              "amount <> 0",
		"transactions_category_assignment_complete": "(category_id IS NULL AND category_assigned_by = '' AND category_assigned_at IS NULL) OR (category_id IS NOT NULL AND category_assigned_by <> '' AND category_assigned_at IS NOT NULL)",
		"transactions_description_not_blank":        "btrim(description) <> ''",
		"transactions_external_ref_pair":            "(external_ref_provider = '' AND external_ref_provider_transaction_id = '') OR (external_ref_provider <> '' AND external_ref_provider_transaction_id <> '')",
		"transactions_reconciled_requires_ref":      "reconciled = FALSE OR external_ref_provider <> ''",
	}
}
