// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/account"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/predicate"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AccountUpdate) SetKind(v string) *AccountUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableKind(v *string) *AccountUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetBalanceAmount sets the "balance_amount" field.
func (_u *AccountUpdate) SetBalanceAmount(v int64) *AccountUpdate {
	_u.mutation.ResetBalanceAmount()
	_u.mutation.SetBalanceAmount(v)
	return _u
}

// SetNillableBalanceAmount sets the "balance_amount" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBalanceAmount(v *int64) *AccountUpdate {
	if v != nil {
		_u.SetBalanceAmount(*v)
	}
	return _u
}

// AddBalanceAmount adds value to the "balance_amount" field.
func (_u *AccountUpdate) AddBalanceAmount(v int64) *AccountUpdate {
	_u.mutation.AddBalanceAmount(v)
	return _u
}

// SetBalanceCurrency sets the "balance_currency" field.
func (_u *AccountUpdate) SetBalanceCurrency(v string) *AccountUpdate {
	_u.mutation.SetBalanceCurrency(v)
	return _u
}

// SetNillableBalanceCurrency sets the "balance_currency" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBalanceCurrency(v *string) *AccountUpdate {
	if v != nil {
		_u.SetBalanceCurrency(*v)
	}
	return _u
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (_u *AccountUpdate) SetBalanceAsOf(v time.Time) *AccountUpdate {
	_u.mutation.SetBalanceAsOf(v)
	return _u
}

// SetNillableBalanceAsOf sets the "balance_as_of" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableBalanceAsOf(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetBalanceAsOf(*v)
	}
	return _u
}

// SetSourceProvider sets the "source_provider" field.
func (_u *AccountUpdate) SetSourceProvider(v string) *AccountUpdate {
	_u.mutation.SetSourceProvider(v)
	return _u
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSourceProvider(v *string) *AccountUpdate {
	if v != nil {
		_u.SetSourceProvider(*v)
	}
	return _u
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (_u *AccountUpdate) SetSourceProviderAccountID(v string) *AccountUpdate {
	_u.mutation.SetSourceProviderAccountID(v)
	return _u
}

// SetNillableSourceProviderAccountID sets the "source_provider_account_id" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSourceProviderAccountID(v *string) *AccountUpdate {
	if v != nil {
		_u.SetSourceProviderAccountID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(account.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAmount(); ok {
		_spec.SetField(account.FieldBalanceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAmount(); ok {
		_spec.AddField(account.FieldBalanceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BalanceCurrency(); ok {
		_spec.SetField(account.FieldBalanceCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAsOf(); ok {
		_spec.SetField(account.FieldBalanceAsOf, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceProvider(); ok {
		_spec.SetField(account.FieldSourceProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProviderAccountID(); ok {
		_spec.SetField(account.FieldSourceProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AccountUpdateOne) SetKind(v string) *AccountUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableKind(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetBalanceAmount sets the "balance_amount" field.
func (_u *AccountUpdateOne) SetBalanceAmount(v int64) *AccountUpdateOne {
	_u.mutation.ResetBalanceAmount()
	_u.mutation.SetBalanceAmount(v)
	return _u
}

// SetNillableBalanceAmount sets the "balance_amount" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBalanceAmount(v *int64) *AccountUpdateOne {
	if v != nil {
		_u.SetBalanceAmount(*v)
	}
	return _u
}

// AddBalanceAmount adds value to the "balance_amount" field.
func (_u *AccountUpdateOne) AddBalanceAmount(v int64) *AccountUpdateOne {
	_u.mutation.AddBalanceAmount(v)
	return _u
}

// SetBalanceCurrency sets the "balance_currency" field.
func (_u *AccountUpdateOne) SetBalanceCurrency(v string) *AccountUpdateOne {
	_u.mutation.SetBalanceCurrency(v)
	return _u
}

// SetNillableBalanceCurrency sets the "balance_currency" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBalanceCurrency(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetBalanceCurrency(*v)
	}
	return _u
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (_u *AccountUpdateOne) SetBalanceAsOf(v time.Time) *AccountUpdateOne {
	_u.mutation.SetBalanceAsOf(v)
	return _u
}

// SetNillableBalanceAsOf sets the "balance_as_of" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableBalanceAsOf(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetBalanceAsOf(*v)
	}
	return _u
}

// SetSourceProvider sets the "source_provider" field.
func (_u *AccountUpdateOne) SetSourceProvider(v string) *AccountUpdateOne {
	_u.mutation.SetSourceProvider(v)
	return _u
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSourceProvider(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetSourceProvider(*v)
	}
	return _u
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (_u *AccountUpdateOne) SetSourceProviderAccountID(v string) *AccountUpdateOne {
	_u.mutation.SetSourceProviderAccountID(v)
	return _u
}

// SetNillableSourceProviderAccountID sets the "source_provider_account_id" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSourceProviderAccountID(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetSourceProviderAccountID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(account.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAmount(); ok {
		_spec.SetField(account.FieldBalanceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAmount(); ok {
		_spec.AddField(account.FieldBalanceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BalanceCurrency(); ok {
		_spec.SetField(account.FieldBalanceCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAsOf(); ok {
		_spec.SetField(account.FieldBalanceAsOf, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceProvider(); ok {
		_spec.SetField(account.FieldSourceProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProviderAccountID(); ok {
		_spec.SetField(account.FieldSourceProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
