// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/account"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *AccountCreate) SetUserID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AccountCreate) SetName(v string) *AccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *AccountCreate) SetKind(v string) *AccountCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetBalanceAmount sets the "balance_amount" field.
func (_c *AccountCreate) SetBalanceAmount(v int64) *AccountCreate {
	_c.mutation.SetBalanceAmount(v)
	return _c
}

// SetBalanceCurrency sets the "balance_currency" field.
func (_c *AccountCreate) SetBalanceCurrency(v string) *AccountCreate {
	_c.mutation.SetBalanceCurrency(v)
	return _c
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (_c *AccountCreate) SetBalanceAsOf(v time.Time) *AccountCreate {
	_c.mutation.SetBalanceAsOf(v)
	return _c
}

// SetSourceProvider sets the "source_provider" field.
func (_c *AccountCreate) SetSourceProvider(v string) *AccountCreate {
	_c.mutation.SetSourceProvider(v)
	return _c
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSourceProvider(v *string) *AccountCreate {
	if v != nil {
		_c.SetSourceProvider(*v)
	}
	return _c
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (_c *AccountCreate) SetSourceProviderAccountID(v string) *AccountCreate {
	_c.mutation.SetSourceProviderAccountID(v)
	return _c
}

// SetNillableSourceProviderAccountID sets the "source_provider_account_id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSourceProviderAccountID(v *string) *AccountCreate {
	if v != nil {
		_c.SetSourceProviderAccountID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCreate) SetUpdatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.SourceProvider(); !ok {
		v := account.DefaultSourceProvider
		_c.mutation.SetSourceProvider(v)
	}
	if _, ok := _c.mutation.SourceProviderAccountID(); !ok {
		v := account.DefaultSourceProviderAccountID
		_c.mutation.SetSourceProviderAccountID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Account.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Account.name"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Account.kind"`)}
	}
	if _, ok := _c.mutation.BalanceAmount(); !ok {
		return &ValidationError{Name: "balance_amount", err: errors.New(`ent: missing required field "Account.balance_amount"`)}
	}
	if _, ok := _c.mutation.BalanceCurrency(); !ok {
		return &ValidationError{Name: "balance_currency", err: errors.New(`ent: missing required field "Account.balance_currency"`)}
	}
	if _, ok := _c.mutation.BalanceAsOf(); !ok {
		return &ValidationError{Name: "balance_as_of", err: errors.New(`ent: missing required field "Account.balance_as_of"`)}
	}
	if _, ok := _c.mutation.SourceProvider(); !ok {
		return &ValidationError{Name: "source_provider", err: errors.New(`ent: missing required field "Account.source_provider"`)}
	}
	if _, ok := _c.mutation.SourceProviderAccountID(); !ok {
		return &ValidationError{Name: "source_provider_account_id", err: errors.New(`ent: missing required field "Account.source_provider_account_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(account.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(account.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.BalanceAmount(); ok {
		_spec.SetField(account.FieldBalanceAmount, field.TypeInt64, value)
		_node.BalanceAmount = value
	}
	if value, ok := _c.mutation.BalanceCurrency(); ok {
		_spec.SetField(account.FieldBalanceCurrency, field.TypeString, value)
		_node.BalanceCurrency = value
	}
	if value, ok := _c.mutation.BalanceAsOf(); ok {
		_spec.SetField(account.FieldBalanceAsOf, field.TypeTime, value)
		_node.BalanceAsOf = value
	}
	if value, ok := _c.mutation.SourceProvider(); ok {
		_spec.SetField(account.FieldSourceProvider, field.TypeString, value)
		_node.SourceProvider = value
	}
	if value, ok := _c.mutation.SourceProviderAccountID(); ok {
		_spec.SetField(account.FieldSourceProviderAccountID, field.TypeString, value)
		_node.SourceProviderAccountID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	_c.conflict = opts
	return &AccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AccountUpsert) SetName(v string) *AccountUpsert {
	u.Set(account.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsert) UpdateName() *AccountUpsert {
	u.SetExcluded(account.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *AccountUpsert) SetKind(v string) *AccountUpsert {
	u.Set(account.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AccountUpsert) UpdateKind() *AccountUpsert {
	u.SetExcluded(account.FieldKind)
	return u
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *AccountUpsert) SetBalanceAmount(v int64) *AccountUpsert {
	u.Set(account.FieldBalanceAmount, v)
	return u
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *AccountUpsert) UpdateBalanceAmount() *AccountUpsert {
	u.SetExcluded(account.FieldBalanceAmount)
	return u
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *AccountUpsert) AddBalanceAmount(v int64) *AccountUpsert {
	u.Add(account.FieldBalanceAmount, v)
	return u
}

// SetBalanceCurrency sets the "balance_currency" field.
func (u *AccountUpsert) SetBalanceCurrency(v string) *AccountUpsert {
	u.Set(account.FieldBalanceCurrency, v)
	return u
}

// UpdateBalanceCurrency sets the "balance_currency" field to the value that was provided on create.
func (u *AccountUpsert) UpdateBalanceCurrency() *AccountUpsert {
	u.SetExcluded(account.FieldBalanceCurrency)
	return u
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (u *AccountUpsert) SetBalanceAsOf(v time.Time) *AccountUpsert {
	u.Set(account.FieldBalanceAsOf, v)
	return u
}

// UpdateBalanceAsOf sets the "balance_as_of" field to the value that was provided on create.
func (u *AccountUpsert) UpdateBalanceAsOf() *AccountUpsert {
	u.SetExcluded(account.FieldBalanceAsOf)
	return u
}

// SetSourceProvider sets the "source_provider" field.
func (u *AccountUpsert) SetSourceProvider(v string) *AccountUpsert {
	u.Set(account.FieldSourceProvider, v)
	return u
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSourceProvider() *AccountUpsert {
	u.SetExcluded(account.FieldSourceProvider)
	return u
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (u *AccountUpsert) SetSourceProviderAccountID(v string) *AccountUpsert {
	u.Set(account.FieldSourceProviderAccountID, v)
	return u
}

// UpdateSourceProviderAccountID sets the "source_provider_account_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSourceProviderAccountID() *AccountUpsert {
	u.SetExcluded(account.FieldSourceProviderAccountID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsert) SetUpdatedAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedAt() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(account.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(account.FieldUserID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AccountUpsertOne) SetName(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateName() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *AccountUpsertOne) SetKind(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateKind() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateKind()
	})
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *AccountUpsertOne) SetBalanceAmount(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceAmount(v)
	})
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *AccountUpsertOne) AddBalanceAmount(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.AddBalanceAmount(v)
	})
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateBalanceAmount() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceAmount()
	})
}

// SetBalanceCurrency sets the "balance_currency" field.
func (u *AccountUpsertOne) SetBalanceCurrency(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceCurrency(v)
	})
}

// UpdateBalanceCurrency sets the "balance_currency" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateBalanceCurrency() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceCurrency()
	})
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (u *AccountUpsertOne) SetBalanceAsOf(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceAsOf(v)
	})
}

// UpdateBalanceAsOf sets the "balance_as_of" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateBalanceAsOf() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceAsOf()
	})
}

// SetSourceProvider sets the "source_provider" field.
func (u *AccountUpsertOne) SetSourceProvider(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSourceProvider(v)
	})
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSourceProvider() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSourceProvider()
	})
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (u *AccountUpsertOne) SetSourceProviderAccountID(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSourceProviderAccountID(v)
	})
}

// UpdateSourceProviderAccountID sets the "source_provider_account_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSourceProviderAccountID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSourceProviderAccountID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertOne) SetUpdatedAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountUpsertOne.ID is not supported by MySQL driver. Use AccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	_c.conflict = opts
	return &AccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: _c,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(account.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(account.FieldUserID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AccountUpsertBulk) SetName(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateName() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *AccountUpsertBulk) SetKind(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateKind() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateKind()
	})
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *AccountUpsertBulk) SetBalanceAmount(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceAmount(v)
	})
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *AccountUpsertBulk) AddBalanceAmount(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.AddBalanceAmount(v)
	})
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateBalanceAmount() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceAmount()
	})
}

// SetBalanceCurrency sets the "balance_currency" field.
func (u *AccountUpsertBulk) SetBalanceCurrency(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceCurrency(v)
	})
}

// UpdateBalanceCurrency sets the "balance_currency" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateBalanceCurrency() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceCurrency()
	})
}

// SetBalanceAsOf sets the "balance_as_of" field.
func (u *AccountUpsertBulk) SetBalanceAsOf(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetBalanceAsOf(v)
	})
}

// UpdateBalanceAsOf sets the "balance_as_of" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateBalanceAsOf() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateBalanceAsOf()
	})
}

// SetSourceProvider sets the "source_provider" field.
func (u *AccountUpsertBulk) SetSourceProvider(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSourceProvider(v)
	})
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSourceProvider() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSourceProvider()
	})
}

// SetSourceProviderAccountID sets the "source_provider_account_id" field.
func (u *AccountUpsertBulk) SetSourceProviderAccountID(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSourceProviderAccountID(v)
	})
}

// UpdateSourceProviderAccountID sets the "source_provider_account_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSourceProviderAccountID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSourceProviderAccountID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
