// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/category"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/categoryrule"
)

// CategoryRuleCreate is the builder for creating a CategoryRule entity.
type CategoryRuleCreate struct {
	config
	mutation *CategoryRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCategoryID sets the "category_id" field.
func (_c *CategoryRuleCreate) SetCategoryID(v uuid.UUID) *CategoryRuleCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetKeyword sets the "keyword" field.
func (_c *CategoryRuleCreate) SetKeyword(v string) *CategoryRuleCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CategoryRuleCreate) SetCreatedAt(v time.Time) *CategoryRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CategoryRuleCreate) SetNillableCreatedAt(v *time.Time) *CategoryRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CategoryRuleCreate) SetID(v uuid.UUID) *CategoryRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *CategoryRuleCreate) SetCategory(v *Category) *CategoryRuleCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the CategoryRuleMutation object of the builder.
func (_c *CategoryRuleCreate) Mutation() *CategoryRuleMutation {
	return _c.mutation
}

// Save creates the CategoryRule in the database.
func (_c *CategoryRuleCreate) Save(ctx context.Context) (*CategoryRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CategoryRuleCreate) SaveX(ctx context.Context) *CategoryRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CategoryRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := categoryrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CategoryRuleCreate) check() error {
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "CategoryRule.category_id"`)}
	}
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "CategoryRule.keyword"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CategoryRule.created_at"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "CategoryRule.category"`)}
	}
	return nil
}

func (_c *CategoryRuleCreate) sqlSave(ctx context.Context) (*CategoryRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CategoryRuleCreate) createSpec() (*CategoryRule, *sqlgraph.CreateSpec) {
	var (
		_node = &CategoryRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(categoryrule.Table, sqlgraph.NewFieldSpec(categoryrule.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(categoryrule.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(categoryrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   categoryrule.CategoryTable,
			Columns: []string{categoryrule.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CategoryRule.Create().
//		SetCategoryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryRuleUpsert) {
//			SetCategoryID(v+v).
//		}).
//		Exec(ctx)
func (_c *CategoryRuleCreate) OnConflict(opts ...sql.ConflictOption) *CategoryRuleUpsertOne {
	_c.conflict = opts
	return &CategoryRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CategoryRuleCreate) OnConflictColumns(columns ...string) *CategoryRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CategoryRuleUpsertOne{
		create: _c,
	}
}

type (
	// CategoryRuleUpsertOne is the builder for "upsert"-ing
	//  one CategoryRule node.
	CategoryRuleUpsertOne struct {
		create *CategoryRuleCreate
	}

	// CategoryRuleUpsert is the "OnConflict" setter.
	CategoryRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetCategoryID sets the "category_id" field.
func (u *CategoryRuleUpsert) SetCategoryID(v uuid.UUID) *CategoryRuleUpsert {
	u.Set(categoryrule.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *CategoryRuleUpsert) UpdateCategoryID() *CategoryRuleUpsert {
	u.SetExcluded(categoryrule.FieldCategoryID)
	return u
}

// SetKeyword sets the "keyword" field.
func (u *CategoryRuleUpsert) SetKeyword(v string) *CategoryRuleUpsert {
	u.Set(categoryrule.FieldKeyword, v)
	return u
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *CategoryRuleUpsert) UpdateKeyword() *CategoryRuleUpsert {
	u.SetExcluded(categoryrule.FieldKeyword)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(categoryrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CategoryRuleUpsertOne) UpdateNewValues() *CategoryRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(categoryrule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(categoryrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CategoryRuleUpsertOne) Ignore() *CategoryRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryRuleUpsertOne) DoNothing() *CategoryRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryRuleCreate.OnConflict
// documentation for more info.
func (u *CategoryRuleUpsertOne) Update(set func(*CategoryRuleUpsert)) *CategoryRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *CategoryRuleUpsertOne) SetCategoryID(v uuid.UUID) *CategoryRuleUpsertOne {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *CategoryRuleUpsertOne) UpdateCategoryID() *CategoryRuleUpsertOne {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.UpdateCategoryID()
	})
}

// SetKeyword sets the "keyword" field.
func (u *CategoryRuleUpsertOne) SetKeyword(v string) *CategoryRuleUpsertOne {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.SetKeyword(v)
	})
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *CategoryRuleUpsertOne) UpdateKeyword() *CategoryRuleUpsertOne {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.UpdateKeyword()
	})
}

// Exec executes the query.
func (u *CategoryRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CategoryRuleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CategoryRuleUpsertOne.ID is not supported by MySQL driver. Use CategoryRuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CategoryRuleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CategoryRuleCreateBulk is the builder for creating many CategoryRule entities in bulk.
type CategoryRuleCreateBulk struct {
	config
	err      error
	builders []*CategoryRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the CategoryRule entities in the database.
func (_c *CategoryRuleCreateBulk) Save(ctx context.Context) ([]*CategoryRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CategoryRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CategoryRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CategoryRuleCreateBulk) SaveX(ctx context.Context) []*CategoryRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CategoryRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryRuleUpsert) {
//			SetCategoryID(v+v).
//		}).
//		Exec(ctx)
func (_c *CategoryRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *CategoryRuleUpsertBulk {
	_c.conflict = opts
	return &CategoryRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CategoryRuleCreateBulk) OnConflictColumns(columns ...string) *CategoryRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CategoryRuleUpsertBulk{
		create: _c,
	}
}

// CategoryRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of CategoryRule nodes.
type CategoryRuleUpsertBulk struct {
	create *CategoryRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(categoryrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CategoryRuleUpsertBulk) UpdateNewValues() *CategoryRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(categoryrule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(categoryrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CategoryRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CategoryRuleUpsertBulk) Ignore() *CategoryRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryRuleUpsertBulk) DoNothing() *CategoryRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryRuleCreateBulk.OnConflict
// documentation for more info.
func (u *CategoryRuleUpsertBulk) Update(set func(*CategoryRuleUpsert)) *CategoryRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *CategoryRuleUpsertBulk) SetCategoryID(v uuid.UUID) *CategoryRuleUpsertBulk {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *CategoryRuleUpsertBulk) UpdateCategoryID() *CategoryRuleUpsertBulk {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.UpdateCategoryID()
	})
}

// SetKeyword sets the "keyword" field.
func (u *CategoryRuleUpsertBulk) SetKeyword(v string) *CategoryRuleUpsertBulk {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.SetKeyword(v)
	})
}

// UpdateKeyword sets the "keyword" field to the value that was provided on create.
func (u *CategoryRuleUpsertBulk) UpdateKeyword() *CategoryRuleUpsertBulk {
	return u.Update(func(s *CategoryRuleUpsert) {
		s.UpdateKeyword()
	})
}

// Exec executes the query.
func (u *CategoryRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CategoryRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
