// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/categoryrule"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/predicate"
)

// CategoryRuleDelete is the builder for deleting a CategoryRule entity.
type CategoryRuleDelete struct {
	config
	hooks    []Hook
	mutation *CategoryRuleMutation
}

// Where appends a list predicates to the CategoryRuleDelete builder.
func (_d *CategoryRuleDelete) Where(ps ...predicate.CategoryRule) *CategoryRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CategoryRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CategoryRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(categoryrule.Table, sqlgraph.NewFieldSpec(categoryrule.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CategoryRuleDeleteOne is the builder for deleting a single CategoryRule entity.
type CategoryRuleDeleteOne struct {
	_d *CategoryRuleDelete
}

// Where appends a list predicates to the CategoryRuleDelete builder.
func (_d *CategoryRuleDeleteOne) Where(ps ...predicate.CategoryRule) *CategoryRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CategoryRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{categoryrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
