// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/account"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/category"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/categoryrule"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/schema"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/transaction"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescSourceProvider is the schema descriptor for source_provider field.
	accountDescSourceProvider := accountFields[7].Descriptor()
	// account.DefaultSourceProvider holds the default value on creation for the source_provider field.
	account.DefaultSourceProvider = accountDescSourceProvider.Default.(string)
	// accountDescSourceProviderAccountID is the schema descriptor for source_provider_account_id field.
	accountDescSourceProviderAccountID := accountFields[8].Descriptor()
	// account.DefaultSourceProviderAccountID holds the default value on creation for the source_provider_account_id field.
	account.DefaultSourceProviderAccountID = accountDescSourceProviderAccountID.Default.(string)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[9].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[10].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[4].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[5].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	categoryruleFields := schema.CategoryRule{}.Fields()
	_ = categoryruleFields
	// categoryruleDescCreatedAt is the schema descriptor for created_at field.
	categoryruleDescCreatedAt := categoryruleFields[3].Descriptor()
	// categoryrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	categoryrule.DefaultCreatedAt = categoryruleDescCreatedAt.Default.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescReconciled is the schema descriptor for reconciled field.
	transactionDescReconciled := transactionFields[7].Descriptor()
	// transaction.DefaultReconciled holds the default value on creation for the reconciled field.
	transaction.DefaultReconciled = transactionDescReconciled.Default.(bool)
	// transactionDescCategoryAssignedBy is the schema descriptor for category_assigned_by field.
	transactionDescCategoryAssignedBy := transactionFields[9].Descriptor()
	// transaction.DefaultCategoryAssignedBy holds the default value on creation for the category_assigned_by field.
	transaction.DefaultCategoryAssignedBy = transactionDescCategoryAssignedBy.Default.(string)
	// transactionDescExternalRefProvider is the schema descriptor for external_ref_provider field.
	transactionDescExternalRefProvider := transactionFields[11].Descriptor()
	// transaction.DefaultExternalRefProvider holds the default value on creation for the external_ref_provider field.
	transaction.DefaultExternalRefProvider = transactionDescExternalRefProvider.Default.(string)
	// transactionDescExternalRefProviderTransactionID is the schema descriptor for external_ref_provider_transaction_id field.
	transactionDescExternalRefProviderTransactionID := transactionFields[12].Descriptor()
	// transaction.DefaultExternalRefProviderTransactionID holds the default value on creation for the external_ref_provider_transaction_id field.
	transaction.DefaultExternalRefProviderTransactionID = transactionDescExternalRefProviderTransactionID.Default.(string)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[13].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionFields[14].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
