// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/transaction"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID uuid.UUID `json:"account_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Reconciled holds the value of the "reconciled" field.
	Reconciled bool `json:"reconciled,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID *uuid.UUID `json:"category_id,omitempty"`
	// CategoryAssignedBy holds the value of the "category_assigned_by" field.
	CategoryAssignedBy string `json:"category_assigned_by,omitempty"`
	// CategoryAssignedAt holds the value of the "category_assigned_at" field.
	CategoryAssignedAt *time.Time `json:"category_assigned_at,omitempty"`
	// ExternalRefProvider holds the value of the "external_ref_provider" field.
	ExternalRefProvider string `json:"external_ref_provider,omitempty"`
	// ExternalRefProviderTransactionID holds the value of the "external_ref_provider_transaction_id" field.
	ExternalRefProviderTransactionID string `json:"external_ref_provider_transaction_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldCategoryID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case transaction.FieldReconciled:
			values[i] = new(sql.NullBool)
		case transaction.FieldAmount:
			values[i] = new(sql.NullInt64)
		case transaction.FieldCurrency, transaction.FieldDescription, transaction.FieldCategoryAssignedBy, transaction.FieldExternalRefProvider, transaction.FieldExternalRefProviderTransactionID:
			values[i] = new(sql.NullString)
		case transaction.FieldOccurredAt, transaction.FieldCategoryAssignedAt, transaction.FieldCreatedAt, transaction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case transaction.FieldID, transaction.FieldUserID, transaction.FieldAccountID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (_m *Transaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case transaction.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case transaction.FieldAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value != nil {
				_m.AccountID = *value
			}
		case transaction.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case transaction.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case transaction.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case transaction.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case transaction.FieldReconciled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reconciled", values[i])
			} else if value.Valid {
				_m.Reconciled = value.Bool
			}
		case transaction.FieldCategoryID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = new(uuid.UUID)
				*_m.CategoryID = *value.S.(*uuid.UUID)
			}
		case transaction.FieldCategoryAssignedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_assigned_by", values[i])
			} else if value.Valid {
				_m.CategoryAssignedBy = value.String
			}
		case transaction.FieldCategoryAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field category_assigned_at", values[i])
			} else if value.Valid {
				_m.CategoryAssignedAt = new(time.Time)
				*_m.CategoryAssignedAt = value.Time
			}
		case transaction.FieldExternalRefProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_ref_provider", values[i])
			} else if value.Valid {
				_m.ExternalRefProvider = value.String
			}
		case transaction.FieldExternalRefProviderTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_ref_provider_transaction_id", values[i])
			} else if value.Valid {
				_m.ExternalRefProviderTransactionID = value.String
			}
		case transaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transaction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transaction.
// This includes values selected through modifiers, order, etc.
func (_m *Transaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Transaction) Update() *TransactionUpdateOne {
	return NewTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Transaction) Unwrap() *Transaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("reconciled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reconciled))
	builder.WriteString(", ")
	if v := _m.CategoryID; v != nil {
		builder.WriteString("category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("category_assigned_by=")
	builder.WriteString(_m.CategoryAssignedBy)
	builder.WriteString(", ")
	if v := _m.CategoryAssignedAt; v != nil {
		builder.WriteString("category_assigned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("external_ref_provider=")
	builder.WriteString(_m.ExternalRefProvider)
	builder.WriteString(", ")
	builder.WriteString("external_ref_provider_transaction_id=")
	builder.WriteString(_m.ExternalRefProviderTransactionID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction
