// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/predicate"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/transaction"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v int64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *int64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v int64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TransactionUpdate) SetCurrency(v string) *TransactionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCurrency(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *TransactionUpdate) SetOccurredAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableOccurredAt(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdate) SetDescription(v string) *TransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDescription(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetReconciled sets the "reconciled" field.
func (_u *TransactionUpdate) SetReconciled(v bool) *TransactionUpdate {
	_u.mutation.SetReconciled(v)
	return _u
}

// SetNillableReconciled sets the "reconciled" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableReconciled(v *bool) *TransactionUpdate {
	if v != nil {
		_u.SetReconciled(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *TransactionUpdate) SetCategoryID(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategoryID(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *TransactionUpdate) ClearCategoryID() *TransactionUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (_u *TransactionUpdate) SetCategoryAssignedBy(v string) *TransactionUpdate {
	_u.mutation.SetCategoryAssignedBy(v)
	return _u
}

// SetNillableCategoryAssignedBy sets the "category_assigned_by" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategoryAssignedBy(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetCategoryAssignedBy(*v)
	}
	return _u
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (_u *TransactionUpdate) SetCategoryAssignedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetCategoryAssignedAt(v)
	return _u
}

// SetNillableCategoryAssignedAt sets the "category_assigned_at" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategoryAssignedAt(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetCategoryAssignedAt(*v)
	}
	return _u
}

// ClearCategoryAssignedAt clears the value of the "category_assigned_at" field.
func (_u *TransactionUpdate) ClearCategoryAssignedAt() *TransactionUpdate {
	_u.mutation.ClearCategoryAssignedAt()
	return _u
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (_u *TransactionUpdate) SetExternalRefProvider(v string) *TransactionUpdate {
	_u.mutation.SetExternalRefProvider(v)
	return _u
}

// SetNillableExternalRefProvider sets the "external_ref_provider" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableExternalRefProvider(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetExternalRefProvider(*v)
	}
	return _u
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (_u *TransactionUpdate) SetExternalRefProviderTransactionID(v string) *TransactionUpdate {
	_u.mutation.SetExternalRefProviderTransactionID(v)
	return _u
}

// SetNillableExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableExternalRefProviderTransactionID(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetExternalRefProviderTransactionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdate) SetUpdatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(transaction.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reconciled(); ok {
		_spec.SetField(transaction.FieldReconciled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(transaction.FieldCategoryID, field.TypeUUID, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(transaction.FieldCategoryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CategoryAssignedBy(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryAssignedAt(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoryAssignedAtCleared() {
		_spec.ClearField(transaction.FieldCategoryAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalRefProvider(); ok {
		_spec.SetField(transaction.FieldExternalRefProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalRefProviderTransactionID(); ok {
		_spec.SetField(transaction.FieldExternalRefProviderTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v int64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *int64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v int64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TransactionUpdateOne) SetCurrency(v string) *TransactionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCurrency(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *TransactionUpdateOne) SetOccurredAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableOccurredAt(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdateOne) SetDescription(v string) *TransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDescription(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetReconciled sets the "reconciled" field.
func (_u *TransactionUpdateOne) SetReconciled(v bool) *TransactionUpdateOne {
	_u.mutation.SetReconciled(v)
	return _u
}

// SetNillableReconciled sets the "reconciled" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableReconciled(v *bool) *TransactionUpdateOne {
	if v != nil {
		_u.SetReconciled(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *TransactionUpdateOne) SetCategoryID(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategoryID(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *TransactionUpdateOne) ClearCategoryID() *TransactionUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (_u *TransactionUpdateOne) SetCategoryAssignedBy(v string) *TransactionUpdateOne {
	_u.mutation.SetCategoryAssignedBy(v)
	return _u
}

// SetNillableCategoryAssignedBy sets the "category_assigned_by" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategoryAssignedBy(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetCategoryAssignedBy(*v)
	}
	return _u
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (_u *TransactionUpdateOne) SetCategoryAssignedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetCategoryAssignedAt(v)
	return _u
}

// SetNillableCategoryAssignedAt sets the "category_assigned_at" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategoryAssignedAt(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetCategoryAssignedAt(*v)
	}
	return _u
}

// ClearCategoryAssignedAt clears the value of the "category_assigned_at" field.
func (_u *TransactionUpdateOne) ClearCategoryAssignedAt() *TransactionUpdateOne {
	_u.mutation.ClearCategoryAssignedAt()
	return _u
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (_u *TransactionUpdateOne) SetExternalRefProvider(v string) *TransactionUpdateOne {
	_u.mutation.SetExternalRefProvider(v)
	return _u
}

// SetNillableExternalRefProvider sets the "external_ref_provider" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableExternalRefProvider(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetExternalRefProvider(*v)
	}
	return _u
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (_u *TransactionUpdateOne) SetExternalRefProviderTransactionID(v string) *TransactionUpdateOne {
	_u.mutation.SetExternalRefProviderTransactionID(v)
	return _u
}

// SetNillableExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableExternalRefProviderTransactionID(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetExternalRefProviderTransactionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdateOne) SetUpdatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(transaction.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reconciled(); ok {
		_spec.SetField(transaction.FieldReconciled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(transaction.FieldCategoryID, field.TypeUUID, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(transaction.FieldCategoryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CategoryAssignedBy(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryAssignedAt(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoryAssignedAtCleared() {
		_spec.ClearField(transaction.FieldCategoryAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalRefProvider(); ok {
		_spec.SetField(transaction.FieldExternalRefProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalRefProviderTransactionID(); ok {
		_spec.SetField(transaction.FieldExternalRefProviderTransactionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
