// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/transaction"
)

// TransactionCreate is the builder for creating a Transaction entity.
type TransactionCreate struct {
	config
	mutation *TransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *TransactionCreate) SetUserID(v uuid.UUID) *TransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *TransactionCreate) SetAccountID(v uuid.UUID) *TransactionCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TransactionCreate) SetAmount(v int64) *TransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *TransactionCreate) SetCurrency(v string) *TransactionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *TransactionCreate) SetOccurredAt(v time.Time) *TransactionCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TransactionCreate) SetDescription(v string) *TransactionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetReconciled sets the "reconciled" field.
func (_c *TransactionCreate) SetReconciled(v bool) *TransactionCreate {
	_c.mutation.SetReconciled(v)
	return _c
}

// SetNillableReconciled sets the "reconciled" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableReconciled(v *bool) *TransactionCreate {
	if v != nil {
		_c.SetReconciled(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *TransactionCreate) SetCategoryID(v uuid.UUID) *TransactionCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCategoryID(v *uuid.UUID) *TransactionCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (_c *TransactionCreate) SetCategoryAssignedBy(v string) *TransactionCreate {
	_c.mutation.SetCategoryAssignedBy(v)
	return _c
}

// SetNillableCategoryAssignedBy sets the "category_assigned_by" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCategoryAssignedBy(v *string) *TransactionCreate {
	if v != nil {
		_c.SetCategoryAssignedBy(*v)
	}
	return _c
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (_c *TransactionCreate) SetCategoryAssignedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetCategoryAssignedAt(v)
	return _c
}

// SetNillableCategoryAssignedAt sets the "category_assigned_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCategoryAssignedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetCategoryAssignedAt(*v)
	}
	return _c
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (_c *TransactionCreate) SetExternalRefProvider(v string) *TransactionCreate {
	_c.mutation.SetExternalRefProvider(v)
	return _c
}

// SetNillableExternalRefProvider sets the "external_ref_provider" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableExternalRefProvider(v *string) *TransactionCreate {
	if v != nil {
		_c.SetExternalRefProvider(*v)
	}
	return _c
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (_c *TransactionCreate) SetExternalRefProviderTransactionID(v string) *TransactionCreate {
	_c.mutation.SetExternalRefProviderTransactionID(v)
	return _c
}

// SetNillableExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableExternalRefProviderTransactionID(v *string) *TransactionCreate {
	if v != nil {
		_c.SetExternalRefProviderTransactionID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransactionCreate) SetCreatedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCreatedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TransactionCreate) SetUpdatedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableUpdatedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransactionCreate) SetID(v uuid.UUID) *TransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TransactionMutation object of the builder.
func (_c *TransactionCreate) Mutation() *TransactionMutation {
	return _c.mutation
}

// Save creates the Transaction in the database.
func (_c *TransactionCreate) Save(ctx context.Context) (*Transaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionCreate) SaveX(ctx context.Context) *Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransactionCreate) defaults() {
	if _, ok := _c.mutation.Reconciled(); !ok {
		v := transaction.DefaultReconciled
		_c.mutation.SetReconciled(v)
	}
	if _, ok := _c.mutation.CategoryAssignedBy(); !ok {
		v := transaction.DefaultCategoryAssignedBy
		_c.mutation.SetCategoryAssignedBy(v)
	}
	if _, ok := _c.mutation.ExternalRefProvider(); !ok {
		v := transaction.DefaultExternalRefProvider
		_c.mutation.SetExternalRefProvider(v)
	}
	if _, ok := _c.mutation.ExternalRefProviderTransactionID(); !ok {
		v := transaction.DefaultExternalRefProviderTransactionID
		_c.mutation.SetExternalRefProviderTransactionID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := transaction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Transaction.user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Transaction.account_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Transaction.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Transaction.currency"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "Transaction.occurred_at"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Transaction.description"`)}
	}
	if _, ok := _c.mutation.Reconciled(); !ok {
		return &ValidationError{Name: "reconciled", err: errors.New(`ent: missing required field "Transaction.reconciled"`)}
	}
	if _, ok := _c.mutation.CategoryAssignedBy(); !ok {
		return &ValidationError{Name: "category_assigned_by", err: errors.New(`ent: missing required field "Transaction.category_assigned_by"`)}
	}
	if _, ok := _c.mutation.ExternalRefProvider(); !ok {
		return &ValidationError{Name: "external_ref_provider", err: errors.New(`ent: missing required field "Transaction.external_ref_provider"`)}
	}
	if _, ok := _c.mutation.ExternalRefProviderTransactionID(); !ok {
		return &ValidationError{Name: "external_ref_provider_transaction_id", err: errors.New(`ent: missing required field "Transaction.external_ref_provider_transaction_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Transaction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Transaction.updated_at"`)}
	}
	return nil
}

func (_c *TransactionCreate) sqlSave(ctx context.Context) (*Transaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionCreate) createSpec() (*Transaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Transaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transaction.Table, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(transaction.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(transaction.FieldAccountID, field.TypeUUID, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(transaction.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Reconciled(); ok {
		_spec.SetField(transaction.FieldReconciled, field.TypeBool, value)
		_node.Reconciled = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(transaction.FieldCategoryID, field.TypeUUID, value)
		_node.CategoryID = &value
	}
	if value, ok := _c.mutation.CategoryAssignedBy(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedBy, field.TypeString, value)
		_node.CategoryAssignedBy = value
	}
	if value, ok := _c.mutation.CategoryAssignedAt(); ok {
		_spec.SetField(transaction.FieldCategoryAssignedAt, field.TypeTime, value)
		_node.CategoryAssignedAt = &value
	}
	if value, ok := _c.mutation.ExternalRefProvider(); ok {
		_spec.SetField(transaction.FieldExternalRefProvider, field.TypeString, value)
		_node.ExternalRefProvider = value
	}
	if value, ok := _c.mutation.ExternalRefProviderTransactionID(); ok {
		_spec.SetField(transaction.FieldExternalRefProviderTransactionID, field.TypeString, value)
		_node.ExternalRefProviderTransactionID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Transaction.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *TransactionCreate) OnConflict(opts ...sql.ConflictOption) *TransactionUpsertOne {
	_c.conflict = opts
	return &TransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransactionCreate) OnConflictColumns(columns ...string) *TransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransactionUpsertOne{
		create: _c,
	}
}

type (
	// TransactionUpsertOne is the builder for "upsert"-ing
	//  one Transaction node.
	TransactionUpsertOne struct {
		create *TransactionCreate
	}

	// TransactionUpsert is the "OnConflict" setter.
	TransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetAmount sets the "amount" field.
func (u *TransactionUpsert) SetAmount(v int64) *TransactionUpsert {
	u.Set(transaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateAmount() *TransactionUpsert {
	u.SetExcluded(transaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsert) AddAmount(v int64) *TransactionUpsert {
	u.Add(transaction.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *TransactionUpsert) SetCurrency(v string) *TransactionUpsert {
	u.Set(transaction.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCurrency() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCurrency)
	return u
}

// SetOccurredAt sets the "occurred_at" field.
func (u *TransactionUpsert) SetOccurredAt(v time.Time) *TransactionUpsert {
	u.Set(transaction.FieldOccurredAt, v)
	return u
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateOccurredAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldOccurredAt)
	return u
}

// SetDescription sets the "description" field.
func (u *TransactionUpsert) SetDescription(v string) *TransactionUpsert {
	u.Set(transaction.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateDescription() *TransactionUpsert {
	u.SetExcluded(transaction.FieldDescription)
	return u
}

// SetReconciled sets the "reconciled" field.
func (u *TransactionUpsert) SetReconciled(v bool) *TransactionUpsert {
	u.Set(transaction.FieldReconciled, v)
	return u
}

// UpdateReconciled sets the "reconciled" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateReconciled() *TransactionUpsert {
	u.SetExcluded(transaction.FieldReconciled)
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *TransactionUpsert) SetCategoryID(v uuid.UUID) *TransactionUpsert {
	u.Set(transaction.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCategoryID() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCategoryID)
	return u
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *TransactionUpsert) ClearCategoryID() *TransactionUpsert {
	u.SetNull(transaction.FieldCategoryID)
	return u
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (u *TransactionUpsert) SetCategoryAssignedBy(v string) *TransactionUpsert {
	u.Set(transaction.FieldCategoryAssignedBy, v)
	return u
}

// UpdateCategoryAssignedBy sets the "category_assigned_by" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCategoryAssignedBy() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCategoryAssignedBy)
	return u
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (u *TransactionUpsert) SetCategoryAssignedAt(v time.Time) *TransactionUpsert {
	u.Set(transaction.FieldCategoryAssignedAt, v)
	return u
}

// UpdateCategoryAssignedAt sets the "category_assigned_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCategoryAssignedAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCategoryAssignedAt)
	return u
}

// ClearCategoryAssignedAt clears the value of the "category_assigned_at" field.
func (u *TransactionUpsert) ClearCategoryAssignedAt() *TransactionUpsert {
	u.SetNull(transaction.FieldCategoryAssignedAt)
	return u
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (u *TransactionUpsert) SetExternalRefProvider(v string) *TransactionUpsert {
	u.Set(transaction.FieldExternalRefProvider, v)
	return u
}

// UpdateExternalRefProvider sets the "external_ref_provider" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateExternalRefProvider() *TransactionUpsert {
	u.SetExcluded(transaction.FieldExternalRefProvider)
	return u
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (u *TransactionUpsert) SetExternalRefProviderTransactionID(v string) *TransactionUpsert {
	u.Set(transaction.FieldExternalRefProviderTransactionID, v)
	return u
}

// UpdateExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateExternalRefProviderTransactionID() *TransactionUpsert {
	u.SetExcluded(transaction.FieldExternalRefProviderTransactionID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsert) SetUpdatedAt(v time.Time) *TransactionUpsert {
	u.Set(transaction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateUpdatedAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransactionUpsertOne) UpdateNewValues() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(transaction.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(transaction.FieldUserID)
		}
		if _, exists := u.create.mutation.AccountID(); exists {
			s.SetIgnore(transaction.FieldAccountID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(transaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TransactionUpsertOne) Ignore() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionUpsertOne) DoNothing() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCreate.OnConflict
// documentation for more info.
func (u *TransactionUpsertOne) Update(set func(*TransactionUpsert)) *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetAmount sets the "amount" field.
func (u *TransactionUpsertOne) SetAmount(v int64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsertOne) AddAmount(v int64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateAmount() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *TransactionUpsertOne) SetCurrency(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCurrency() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCurrency()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *TransactionUpsertOne) SetOccurredAt(v time.Time) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateOccurredAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetDescription sets the "description" field.
func (u *TransactionUpsertOne) SetDescription(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateDescription() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateDescription()
	})
}

// SetReconciled sets the "reconciled" field.
func (u *TransactionUpsertOne) SetReconciled(v bool) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetReconciled(v)
	})
}

// UpdateReconciled sets the "reconciled" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateReconciled() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateReconciled()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *TransactionUpsertOne) SetCategoryID(v uuid.UUID) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCategoryID() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *TransactionUpsertOne) ClearCategoryID() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCategoryID()
	})
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (u *TransactionUpsertOne) SetCategoryAssignedBy(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryAssignedBy(v)
	})
}

// UpdateCategoryAssignedBy sets the "category_assigned_by" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCategoryAssignedBy() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryAssignedBy()
	})
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (u *TransactionUpsertOne) SetCategoryAssignedAt(v time.Time) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryAssignedAt(v)
	})
}

// UpdateCategoryAssignedAt sets the "category_assigned_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCategoryAssignedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryAssignedAt()
	})
}

// ClearCategoryAssignedAt clears the value of the "category_assigned_at" field.
func (u *TransactionUpsertOne) ClearCategoryAssignedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCategoryAssignedAt()
	})
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (u *TransactionUpsertOne) SetExternalRefProvider(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExternalRefProvider(v)
	})
}

// UpdateExternalRefProvider sets the "external_ref_provider" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateExternalRefProvider() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExternalRefProvider()
	})
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (u *TransactionUpsertOne) SetExternalRefProviderTransactionID(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExternalRefProviderTransactionID(v)
	})
}

// UpdateExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateExternalRefProviderTransactionID() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExternalRefProviderTransactionID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsertOne) SetUpdatedAt(v time.Time) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateUpdatedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TransactionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TransactionUpsertOne.ID is not supported by MySQL driver. Use TransactionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TransactionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TransactionCreateBulk is the builder for creating many Transaction entities in bulk.
type TransactionCreateBulk struct {
	config
	err      error
	builders []*TransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the Transaction entities in the database.
func (_c *TransactionCreateBulk) Save(ctx context.Context) ([]*Transaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Transaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionCreateBulk) SaveX(ctx context.Context) []*Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Transaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *TransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TransactionUpsertBulk {
	_c.conflict = opts
	return &TransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TransactionCreateBulk) OnConflictColumns(columns ...string) *TransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TransactionUpsertBulk{
		create: _c,
	}
}

// TransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of Transaction nodes.
type TransactionUpsertBulk struct {
	create *TransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransactionUpsertBulk) UpdateNewValues() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(transaction.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(transaction.FieldUserID)
			}
			if _, exists := b.mutation.AccountID(); exists {
				s.SetIgnore(transaction.FieldAccountID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(transaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TransactionUpsertBulk) Ignore() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionUpsertBulk) DoNothing() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCreateBulk.OnConflict
// documentation for more info.
func (u *TransactionUpsertBulk) Update(set func(*TransactionUpsert)) *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetAmount sets the "amount" field.
func (u *TransactionUpsertBulk) SetAmount(v int64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsertBulk) AddAmount(v int64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateAmount() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *TransactionUpsertBulk) SetCurrency(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCurrency() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCurrency()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *TransactionUpsertBulk) SetOccurredAt(v time.Time) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateOccurredAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetDescription sets the "description" field.
func (u *TransactionUpsertBulk) SetDescription(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateDescription() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateDescription()
	})
}

// SetReconciled sets the "reconciled" field.
func (u *TransactionUpsertBulk) SetReconciled(v bool) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetReconciled(v)
	})
}

// UpdateReconciled sets the "reconciled" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateReconciled() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateReconciled()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *TransactionUpsertBulk) SetCategoryID(v uuid.UUID) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCategoryID() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *TransactionUpsertBulk) ClearCategoryID() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCategoryID()
	})
}

// SetCategoryAssignedBy sets the "category_assigned_by" field.
func (u *TransactionUpsertBulk) SetCategoryAssignedBy(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryAssignedBy(v)
	})
}

// UpdateCategoryAssignedBy sets the "category_assigned_by" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCategoryAssignedBy() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryAssignedBy()
	})
}

// SetCategoryAssignedAt sets the "category_assigned_at" field.
func (u *TransactionUpsertBulk) SetCategoryAssignedAt(v time.Time) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCategoryAssignedAt(v)
	})
}

// UpdateCategoryAssignedAt sets the "category_assigned_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCategoryAssignedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCategoryAssignedAt()
	})
}

// ClearCategoryAssignedAt clears the value of the "category_assigned_at" field.
func (u *TransactionUpsertBulk) ClearCategoryAssignedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCategoryAssignedAt()
	})
}

// SetExternalRefProvider sets the "external_ref_provider" field.
func (u *TransactionUpsertBulk) SetExternalRefProvider(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExternalRefProvider(v)
	})
}

// UpdateExternalRefProvider sets the "external_ref_provider" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateExternalRefProvider() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExternalRefProvider()
	})
}

// SetExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field.
func (u *TransactionUpsertBulk) SetExternalRefProviderTransactionID(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExternalRefProviderTransactionID(v)
	})
}

// UpdateExternalRefProviderTransactionID sets the "external_ref_provider_transaction_id" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateExternalRefProviderTransactionID() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExternalRefProviderTransactionID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsertBulk) SetUpdatedAt(v time.Time) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateUpdatedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
