// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// CategoryRule is the predicate function for categoryrule builders.
type CategoryRule func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
