// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldBalanceAmount holds the string denoting the balance_amount field in the database.
	FieldBalanceAmount = "balance_amount"
	// FieldBalanceCurrency holds the string denoting the balance_currency field in the database.
	FieldBalanceCurrency = "balance_currency"
	// FieldBalanceAsOf holds the string denoting the balance_as_of field in the database.
	FieldBalanceAsOf = "balance_as_of"
	// FieldSourceProvider holds the string denoting the source_provider field in the database.
	FieldSourceProvider = "source_provider"
	// FieldSourceProviderAccountID holds the string denoting the source_provider_account_id field in the database.
	FieldSourceProviderAccountID = "source_provider_account_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldKind,
	FieldBalanceAmount,
	FieldBalanceCurrency,
	FieldBalanceAsOf,
	FieldSourceProvider,
	FieldSourceProviderAccountID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSourceProvider holds the default value on creation for the "source_provider" field.
	DefaultSourceProvider string
	// DefaultSourceProviderAccountID holds the default value on creation for the "source_provider_account_id" field.
	DefaultSourceProviderAccountID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByBalanceAmount orders the results by the balance_amount field.
func ByBalanceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAmount, opts...).ToFunc()
}

// ByBalanceCurrency orders the results by the balance_currency field.
func ByBalanceCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceCurrency, opts...).ToFunc()
}

// ByBalanceAsOf orders the results by the balance_as_of field.
func ByBalanceAsOf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAsOf, opts...).ToFunc()
}

// BySourceProvider orders the results by the source_provider field.
func BySourceProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceProvider, opts...).ToFunc()
}

// BySourceProviderAccountID orders the results by the source_provider_account_id field.
func BySourceProviderAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceProviderAccountID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
