// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luigimenezes13/financial-manager/internal/financialtracking/adapter/entrepo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldKind, v))
}

// BalanceAmount applies equality check predicate on the "balance_amount" field. It's identical to BalanceAmountEQ.
func BalanceAmount(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceAmount, v))
}

// BalanceCurrency applies equality check predicate on the "balance_currency" field. It's identical to BalanceCurrencyEQ.
func BalanceCurrency(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceCurrency, v))
}

// BalanceAsOf applies equality check predicate on the "balance_as_of" field. It's identical to BalanceAsOfEQ.
func BalanceAsOf(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceAsOf, v))
}

// SourceProvider applies equality check predicate on the "source_provider" field. It's identical to SourceProviderEQ.
func SourceProvider(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSourceProvider, v))
}

// SourceProviderAccountID applies equality check predicate on the "source_provider_account_id" field. It's identical to SourceProviderAccountIDEQ.
func SourceProviderAccountID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSourceProviderAccountID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldKind, v))
}

// BalanceAmountEQ applies the EQ predicate on the "balance_amount" field.
func BalanceAmountEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceAmount, v))
}

// BalanceAmountNEQ applies the NEQ predicate on the "balance_amount" field.
func BalanceAmountNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldBalanceAmount, v))
}

// BalanceAmountIn applies the In predicate on the "balance_amount" field.
func BalanceAmountIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldBalanceAmount, vs...))
}

// BalanceAmountNotIn applies the NotIn predicate on the "balance_amount" field.
func BalanceAmountNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldBalanceAmount, vs...))
}

// BalanceAmountGT applies the GT predicate on the "balance_amount" field.
func BalanceAmountGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldBalanceAmount, v))
}

// BalanceAmountGTE applies the GTE predicate on the "balance_amount" field.
func BalanceAmountGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldBalanceAmount, v))
}

// BalanceAmountLT applies the LT predicate on the "balance_amount" field.
func BalanceAmountLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldBalanceAmount, v))
}

// BalanceAmountLTE applies the LTE predicate on the "balance_amount" field.
func BalanceAmountLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldBalanceAmount, v))
}

// BalanceCurrencyEQ applies the EQ predicate on the "balance_currency" field.
func BalanceCurrencyEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceCurrency, v))
}

// BalanceCurrencyNEQ applies the NEQ predicate on the "balance_currency" field.
func BalanceCurrencyNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldBalanceCurrency, v))
}

// BalanceCurrencyIn applies the In predicate on the "balance_currency" field.
func BalanceCurrencyIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldBalanceCurrency, vs...))
}

// BalanceCurrencyNotIn applies the NotIn predicate on the "balance_currency" field.
func BalanceCurrencyNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldBalanceCurrency, vs...))
}

// BalanceCurrencyGT applies the GT predicate on the "balance_currency" field.
func BalanceCurrencyGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldBalanceCurrency, v))
}

// BalanceCurrencyGTE applies the GTE predicate on the "balance_currency" field.
func BalanceCurrencyGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldBalanceCurrency, v))
}

// BalanceCurrencyLT applies the LT predicate on the "balance_currency" field.
func BalanceCurrencyLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldBalanceCurrency, v))
}

// BalanceCurrencyLTE applies the LTE predicate on the "balance_currency" field.
func BalanceCurrencyLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldBalanceCurrency, v))
}

// BalanceCurrencyContains applies the Contains predicate on the "balance_currency" field.
func BalanceCurrencyContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldBalanceCurrency, v))
}

// BalanceCurrencyHasPrefix applies the HasPrefix predicate on the "balance_currency" field.
func BalanceCurrencyHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldBalanceCurrency, v))
}

// BalanceCurrencyHasSuffix applies the HasSuffix predicate on the "balance_currency" field.
func BalanceCurrencyHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldBalanceCurrency, v))
}

// BalanceCurrencyEqualFold applies the EqualFold predicate on the "balance_currency" field.
func BalanceCurrencyEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldBalanceCurrency, v))
}

// BalanceCurrencyContainsFold applies the ContainsFold predicate on the "balance_currency" field.
func BalanceCurrencyContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldBalanceCurrency, v))
}

// BalanceAsOfEQ applies the EQ predicate on the "balance_as_of" field.
func BalanceAsOfEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldBalanceAsOf, v))
}

// BalanceAsOfNEQ applies the NEQ predicate on the "balance_as_of" field.
func BalanceAsOfNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldBalanceAsOf, v))
}

// BalanceAsOfIn applies the In predicate on the "balance_as_of" field.
func BalanceAsOfIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldBalanceAsOf, vs...))
}

// BalanceAsOfNotIn applies the NotIn predicate on the "balance_as_of" field.
func BalanceAsOfNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldBalanceAsOf, vs...))
}

// BalanceAsOfGT applies the GT predicate on the "balance_as_of" field.
func BalanceAsOfGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldBalanceAsOf, v))
}

// BalanceAsOfGTE applies the GTE predicate on the "balance_as_of" field.
func BalanceAsOfGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldBalanceAsOf, v))
}

// BalanceAsOfLT applies the LT predicate on the "balance_as_of" field.
func BalanceAsOfLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldBalanceAsOf, v))
}

// BalanceAsOfLTE applies the LTE predicate on the "balance_as_of" field.
func BalanceAsOfLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldBalanceAsOf, v))
}

// SourceProviderEQ applies the EQ predicate on the "source_provider" field.
func SourceProviderEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSourceProvider, v))
}

// SourceProviderNEQ applies the NEQ predicate on the "source_provider" field.
func SourceProviderNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSourceProvider, v))
}

// SourceProviderIn applies the In predicate on the "source_provider" field.
func SourceProviderIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSourceProvider, vs...))
}

// SourceProviderNotIn applies the NotIn predicate on the "source_provider" field.
func SourceProviderNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSourceProvider, vs...))
}

// SourceProviderGT applies the GT predicate on the "source_provider" field.
func SourceProviderGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSourceProvider, v))
}

// SourceProviderGTE applies the GTE predicate on the "source_provider" field.
func SourceProviderGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSourceProvider, v))
}

// SourceProviderLT applies the LT predicate on the "source_provider" field.
func SourceProviderLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSourceProvider, v))
}

// SourceProviderLTE applies the LTE predicate on the "source_provider" field.
func SourceProviderLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSourceProvider, v))
}

// SourceProviderContains applies the Contains predicate on the "source_provider" field.
func SourceProviderContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSourceProvider, v))
}

// SourceProviderHasPrefix applies the HasPrefix predicate on the "source_provider" field.
func SourceProviderHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSourceProvider, v))
}

// SourceProviderHasSuffix applies the HasSuffix predicate on the "source_provider" field.
func SourceProviderHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSourceProvider, v))
}

// SourceProviderEqualFold applies the EqualFold predicate on the "source_provider" field.
func SourceProviderEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSourceProvider, v))
}

// SourceProviderContainsFold applies the ContainsFold predicate on the "source_provider" field.
func SourceProviderContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSourceProvider, v))
}

// SourceProviderAccountIDEQ applies the EQ predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDNEQ applies the NEQ predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDIn applies the In predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSourceProviderAccountID, vs...))
}

// SourceProviderAccountIDNotIn applies the NotIn predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSourceProviderAccountID, vs...))
}

// SourceProviderAccountIDGT applies the GT predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDGTE applies the GTE predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDLT applies the LT predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDLTE applies the LTE predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDContains applies the Contains predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDHasPrefix applies the HasPrefix predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDHasSuffix applies the HasSuffix predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDEqualFold applies the EqualFold predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSourceProviderAccountID, v))
}

// SourceProviderAccountIDContainsFold applies the ContainsFold predicate on the "source_provider_account_id" field.
func SourceProviderAccountIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSourceProviderAccountID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
